### PR TITLE
fix: 'unable to start service init-kasmvnc-config' error on some file systems - notably ZFS

### PR DESCRIPTION
**Pull request by snippetsBySam**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-baseimage-kasmvnc/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

There is an issue that occurs on some file systems which results in the following error message:

`mv: cannot move '/usr/local/etc/kasmvnc/kasmvnc.yaml.lsio' to a subdirectory of itself, '/usr/local/etc/kasmvnc/kasmvnc.yaml'
s6-rc: warning: unable to start service init-kasmvnc-config: command exited 1`

And causes apps based on this base image to fail to run.

This is caused by usage of the move `mv` command to rename the `kasmvnc.yaml.lsio` file. The fix was to change the command from move `mv` to copy `cp` and then delete `rm` the original. This achieves the same goal while allowing the container to be used on these filesystems.

## Benefits of this PR and context:

It fixes the following issues:

https://github.com/linuxserver/docker-calibre/issues/134

https://github.com/linuxserver/docker-calibre/issues/130 (was closed but the issue wasn't fixed)

## How Has This Been Tested?

This was tested by first running the original image that gave the error, and they connecting to the shell, and running the copy/remove commands manually which then fixed the container and allowed the app to run.

### CODE REVIEW

**Comment by aptalca** [comment]
I personally don't think this is appropriate as it's a highly specific band-aid/workaround rather than a solution.

The container processes should be able to successfully move a file within the container filesystem when they are running as root. If they can't, it suggests something seriously wrong with the docker service. Our container init or the upstream apps should be able to do basic operations like a move as long as they have the proper permissions. I have not been able to reproduce this issue.

I would not want to play whack-a-mole with all these operations that may or may not work on some systems.

**Comment by snippetsBySam** [comment]
I understand why this might be seen as a band-fix but this is currently the limit of my abilities.

I've been able to reliably reproduce the issue on 2 systems (One Intel and one AMD based) by doing the following:

-  Clean Install (not in a VM) Ubuntu Desktop 22.04 and on the installer screen with drive/partition options, select "Erase disk and use ZFS" and install Ubuntu as normal
- Next install Docker as normal including the [post-install steps](https://docs.docker.com/engine/install/linux-postinstall/)
- Once done, try to use the docker-calibre image and the error occurs when trying to run the container (shown in the container logs)

**Comment by aptalca** [comment]
See here for the underlying issue: https://forums.docker.com/t/unable-to-run-mv-when-building-any-image-all-mv-is-subdirectory-of-itself/137409

**Comment by snippetsBySam** [comment]
Ahh, thank you, changing the docker storage driver to zfs fixed it without needing this PR

**Pull request closed without merging**
